### ISSUE TITLE
fix some lost formatting

### ISSUE THREAD

**Issue by samccann** [ansible-community/antsibull-docs#221]
Between version 2.3 and 2.4, we lost some formatting on the parameters. [Devel](https://docs.ansible.com/ansible-core/devel/collections/ansible/builtin/git_module.html#parameter-accept_hostkey) works fine:
![image](https://github.com/ansible-community/antsibull-docs/assets/30267855/46ff17da-4420-4358-b267-4afe3192097a)

But [stable-2.15](https://docs.ansible.com/ansible-core/2.15/collections/ansible/builtin/git_module.html#parameter-accept_hostkey) and earlier look as follows:

![image](https://github.com/ansible-community/antsibull-docs/assets/30267855/4a7945c9-81b0-4ead-8413-e3406349fb01)

**Comment by felixfontein** [comment]
That's totally unrelated to antsibull-docs, but related to a PR to ansible-core that ended up in devel and then ansible-core 2.16, but wasn't backported to ansible-core 2.15 and earlier due to semantic markup: https://github.com/ansible/ansible/commit/3e3fb26b35de97f0eddb58b9d47a854e26c4951a#diff-2dfd7c6b151e83dfbc4672ea9daf37445ccc8fc3468bb6d8f8d5f23a294fe5f1L44

**Comment by samccann** [comment]
my bad, sorry for the noise :-)
