### ISSUE TITLE
check_mode attribute description should reflect their support status

### ISSUE THREAD

**Issue by samccann** [ansible-community/antsibull-docs#235]
Right now the attribute description for `check_mode` always says

> Can run in check_mode and return changed status prediction without modifying target

![image](https://github.com/ansible/ansible-documentation/assets/8462645/0032395c-ae1f-4abc-bd5f-6c1b69ecad04)

Even if the module explicitly doesn't support check mode (support `none`) like in the [uri](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html#attributes) example. I can see this being confusing for people reading the docs who might skip over the `Support` side and read `Description` thinking this does support check mode when it does not.

I think the description for entries where check mode isn't supported should be updated to actually say something like "this module does not support check mode" in the field.

Related: https://github.com/ansible/ansible/pull/82427

**Comment by samccann** [comment]
@jborean93  - I suppose we could blank out the description field if the support field == none for all attributes.  What do you think @felixfontein ?

**Comment by felixfontein** [comment]
The text shown here is defined by the module (or plugin) itself, not by antsibull-docs. Most modules use the default text coming from ansible-core's action_common_attributes docs fragment: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/action_common_attributes.py#L13.

Closing since this is unrelated to antsibull-docs.
