### ISSUE TITLE
[RFE] Add support for adding additional sphinx/intersphinx configuration

### ISSUE THREAD

**Issue by tremble** [ansible-community/antsibull-docs#35]
The current [sphinx_init configuration file template](https://github.com/ansible-community/antsibull-docs/blob/main/src/antsibull_docs/data/sphinx_init/conf_py.j2)  doesn't support adding additional intersphinx links.

When moving modules between collections, this leaves a period of time where docs for a collection can't be validated/built because https://docs.ansible.com/ansible/devel/ hasn't been updated to include the new object.inv.

With the AWS collections, because we now have GitHub pages with the docs for 'main' automatically built and pushed, we would be able to inject something like `'amazon_aws': ('https://ansible-collections.github.io/amazon.aws/branch/main/', (None, '../amazon_aws.inv'))` into intersphinx_mapping and as soon as the module has been moved, we'd be able to validate the links in our 'main' branches.

It would be helpful if we could either
1) Specify additional intersphinx links
2) Specify a file, the contents of which would be appended to conf.py
3) Have a standard location in the collection from which antsibull-docs would read and append to conf.py

**Comment by felixfontein** [comment]
For the docs build, I think the form `'amazon_aws': ('https://ansible-collections.github.io/amazon.aws/branch/main/', None)` would be enough ([documentation](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping)). How about a new option `--intersphinx` that can be specified multiple times, in the form `--intersphinx amazon_aws:https://ansible-collections.github.io/amazon.aws/branch/main/ --intersphinx ansible6:https://docs.ansible.com/ansible/6/` (which would add two new entries)? This definitely suffices for a docs build in CI (where cached `.inv` files don't make much sense), and if you want to explicitly configure caching it probably makes sense to modify the generated `conf.py` file anyway since you probably also want to configure other things.

**Comment by felixfontein** [comment]
I've created a first implementation in #44.
